# Generated by Django 5.2.12 on 2026-04-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('oracle_script', models.TextField()),
                ('generated_body', models.TextField(blank=True)),
                ('mistral_model', models.CharField(default='mistral-large-latest', max_length=100)),
                ('wordpress_post_id', models.PositiveIntegerField(blank=True, null=True)),
                ('wordpress_post_type', models.CharField(default='post', max_length=20)),
                ('wordpress_status', models.CharField(default='draft', max_length=20)),
                ('publish_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
