# Generated by Django 5.2.12 on 2026-04-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='wordpress_category_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
