# Generated by Django 5.2.12 on 2026-04-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogentry_wordpress_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='email_notify_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='publish_secret_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
