# Generated by Django 5.2.12 on 2026-04-26 00:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_publish_token_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='approval_status',
            field=models.CharField(choices=[('none', 'N/A (legacy pipeline)'), ('pending_customer', 'Awaiting customer review'), ('approved', 'Approved — scheduled'), ('published', 'Published'), ('rejected', 'Rejected / cancelled')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='customer_brief',
            field=models.TextField(blank=True, help_text='Customer-supplied lines / brief (formatted text).'),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='customer_edited_body',
            field=models.TextField(blank=True, help_text='Last saved version from customer before approval.'),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='draft_email_at',
            field=models.DateTimeField(blank=True, help_text='When we email the draft (publish minus lead hours).', null=True),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='draft_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, help_text='When the post may go live (UTC) if approved.', null=True),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='wp_draft_created_at',
            field=models.DateTimeField(blank=True, help_text='When an approved draft was pushed to WordPress as draft.', null=True),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='oracle_script',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text='Internal note (customer name, campaign, etc.)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_codes_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=64)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, choices=[('text_weekly', 'Text only — 1 post per week ($20/mo)'), ('text_custom', 'Text only — custom posts per week ($20 × posts per week / mo)'), ('images_four', 'Formatted text + 1–2 images — up to 4 blogs per month ($30/mo)')], max_length=32)),
                ('posts_per_week', models.PositiveSmallIntegerField(default=1, help_text='For text plans: 1 = weekly, 2 = twice per week, etc. Multiplies $20/mo base.')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_started_at', models.DateTimeField(blank=True, null=True)),
                ('billing_setup_complete', models.BooleanField(default=False, help_text='Customer confirmed payment method on file (integrate Stripe when ready).')),
                ('paid_current_period', models.BooleanField(default=False, help_text='After the free trial, set True when payment succeeds (e.g. Stripe webhook or admin).')),
                ('publish_weekday', models.PositiveSmallIntegerField(default=2, help_text='0=Monday … 6=Sunday — preferred weekly publish day.')),
                ('publish_time', models.TimeField(default=datetime.time(10, 0), help_text='Local time on publish day.')),
                ('draft_lead_hours', models.PositiveSmallIntegerField(default=48, help_text='How many hours before publish time we email the draft for review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
                ('invite_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='blog.invitecode')),
            ],
        ),
    ]
