# Generated by Django 5.2.13 on 2026-04-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tpmbots_customer_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='used_by_email',
            field=models.EmailField(blank=True, help_text='Email that consumed this code.', max_length=254),
        ),
    ]
