# Generated by Django 5.2.13 on 2026-04-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_invite_code_email_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='invite_code',
        ),
        migrations.DeleteModel(
            name='InviteCode',
        ),
    ]
