# Generated by Django 5.2.13 on 2026-04-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_invite_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='publish_timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone for publish day and time (e.g. America/New_York).', max_length=64),
        ),
    ]
